spring.application.name=library-manager

spring.datasource.url=jdbc:mysql://localhost:3306/library_managerment?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

## 3. ?ÂY LÀ PH?N QUAN TR?NG: Xu?t toàn b? SQL ra file latest_schema.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/latest_schema.sql
#spring.jpa.properties.hibernate.format_sql=true

spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true

logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.transaction=DEBUG

logging.level.org.hibernate.tool.schema=DEBUG

jwt.signerKey=40ef1f41ad760ebd851bcc895aa9e9856a20a59a1565d514e8c1591de94946db